### ISSUE TITLE
Some things I noticed + possible suggestions.

### ISSUE THREAD

**Issue by Sojiro84** [Soft-Bred/Brave-Fox#1]
First of all, thanks for making this good looking theme!

After installing I noticed 2 things, first of which is that the new tab button isn't properly aligned in the middle. See the screenshot.

You can also see in the screenshot, that below the tabs, we have a 1xp dark line. Would it be possible to have that dark line continue following the curves of the tab?

Right now it feel weird so see that black line, then nothing on the tab itself, and then after it continues.

I think it might look better of that black lines follows the tab's design.

![image](https://user-images.githubusercontent.com/13678578/142615396-95b678f3-bf06-4040-917b-83e0f190dc3c.png)

**Comment by JaceThings** [comment]
Funnily enough, that black like shouldn't be there by default. Is that part of your theme or?
If it is part of a custom theme, could you link it so I can test it myself and troubleshoot the problem?

I'll try check out that new tab button problem though, alignment bugs me too

**Comment by Sojiro84** [comment]
Hmm, could be. I am on Linux, KDE Plasma.

If you don't have it then it's or a Linux version issue or part of the Breeze theme that KDE uses.

**Comment by JaceThings** [comment]
Ah, then yea probably a Linux issue (idk how Linux Firefox differs from the others)
But I'll still try some things

**Comment by Sojiro84** [comment]
> Ah, then yea probably a Linux issue (idk how Linux Firefox differs from the others) But I'll still try some things

After some googling I found the fix for the black line below the tab bar:

#nav-bar {
   box-shadow: none !important;
}

![image](https://user-images.githubusercontent.com/13678578/142652032-6bd891be-3718-472a-93c2-5b6d313f402e.png)
