### ISSUE TITLE
Issue with tabs/menu when using theme

### ISSUE THREAD

**Issue by cistine** [Soft-Bred/Brave-Fox#2]
First, very nice theme, so far its the only one I've enjoyed using enough to stick with.

My problem with it is that for reasons I can't seem to recreate, everything above the bookmark bar will stop being interactable. I also have no idea what fixes it. When it happens I can't move tabs, or if I can they'll snap back where they were originally. I also can't interact with the menu for FF, any addon icons, etc. I can't even close the browser window with the X button when it happens.

I can try to get a gif or something of it if needed.

**Comment by JaceThings** [comment]
I honestly can't find a way to recreate this bug, noting in the code messes with intractability with tabs, just the size and looks.

A video/gif would be nice to have, though I can't promise anything since this might be a firefox problem.

None of the other users/myself has ever found this bug, so _maybe_ it's a "you" problem?

**Comment by cistine** [comment]
[https://www.youtube.com/watch?v=zLLgVvH882c](https://www.youtube.com/watch?v=zLLgVvH882c)

[https://puu.sh/IrCyg/703d7679ee.jpg](https://puu.sh/IrCyg/703d7679ee.jpg)

[https://puu.sh/IrCPg/ceaaf37d0b.jpg](https://puu.sh/IrCPg/ceaaf37d0b.jpg)

[https://puu.sh/IrCVp/900d362e1b.jpg](https://puu.sh/IrCVp/900d362e1b.jpg)

The video was done incognito to avoid any addon conflicts, though I did get the same issue outside of it with addons disabled. The first two screenshots are what my tabs look like after moving them around a bit. Sorry the video doesn't have a like, sound or indication of mouse clicks but I assure you I'm clicking all the time on menus, the url bar, etc.

The last SS is of my folder and whats in the userChrome/Content folded. I took the Brave-Fox folder as is and installed it then added the two user folders.

I apologize if this is me messing up something super basic, be it with the installation process or some FF setting I have toggled on/off thats doing this - I'm incredibly inept with FF css things. I also did not have the Remove Overflow.css folder installed.

**Comment by davigamer987** [comment]
I have the same issue

**Comment by aliammar03** [comment]
For me, I fixed it by deleting
 
/* Pin / Un-Pin Tab Animation    */
/* Thanks u/It_Was_The_Other_Guy */
.tabbrowser-tab[fadein]{transition: min-width 250ms linear, max-width 250ms linear !important;}

in the Fancy Animation Zone.css file
