### ISSUE TITLE
Audio playing icon shows over Favicon

### ISSUE THREAD

**Issue by mmattbtw** [Soft-Bred/Brave-Fox#3]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/30363562/145690161-c379ff97-c6a2-45c4-9d4c-29bd64302dec.png">

**Comment by haypp** [comment]
i just disable some code on import.css ,, problem audio playing icon shows over Favicon and some element gone like netflix title promotion fixed ,, i know its stupid solving, i just wanna some sharing

 [Here some element i have disable ](https://i.imgur.com/qmnjUCI.png)
