### ISSUE TITLE
Can't click buttons and url bar after a few hours

### ISSUE THREAD

**Issue by davigamer987** [Soft-Bred/Brave-Fox#4]
I have the same issue as in #2, After a while i can't click the url bar, extensions and tabs, This forces me to restart the browser and is very annoying, Im using arch linux on firefox stable

**Comment by Unbandit2006** [comment]
I have a very similar problem to @davigamer987. Even when I load the webpage right away, I can't use the Close Button for the tab I am on, but for others, I can close, I can't use the back or forward buttons. Luckily I know the keybinds for Firefox, but this is still an inconvenience no one should have to bear with. I am on Windows 10 and stable Firefox Release 97.
